CREATE TABLE employees_1(
	EMP_NO INT(11)
	,BIRTH_DATE DATE NOT NULL 
	,FIRST_NAME VARCHAR(14) NOT NULL
	,LAST_NAME VARCHAR(16) NOT NULL
	,GENDER ENUM('M','F') NOT NULL
	,HIRE_DATE DATE NOT NULL
	,CONSTRAINT PK_EMPLOYEES_EMP_NO PRIMARY KEY(EMP_NO)
);

-- 외래키에는 INDEX 자동 생성;
CREATE TABLE SALARIES_1(
	EMP_NO INT(11) NOT NULL
	,SALARY INT(11) NOT NULL
	,FROM_DATE DATE NOT NULL
	,TO_DATE DATE NOT NULL
	,CONSTRAINT PK_SALARIES_EMP_NO PRIMARY KEY(EMP_NO)
	,CONSTRAINT PK_SALARIES_FROM_DATE PRIMARY KEY(FROM_DATE)
	,CONSTRAINT FK_SALARIES_EMP_NO FOREIGN KEY (EMP_NO) REFERENCES employees_1(EMP_NO)
);


CREATE TABLE titles_1(
	EMP_NO INT(11) NOT NULL
	,title VARCHAR(50) NOT NULL
	,FROM_DATE DATE NOT NULL
	,TO_DATE DATE
	,PRIMARY KEY (EMP_NO,title,FROM_DATE)
);
-- 외래키 이름 설정 및 추가;
alter table titles_1 ADD CONSTRAINT fk_ti_no 
foreign key (EMP_NO) REFERENCES employees_1(EMP_NO);
-- 외래키 삭제;
ALTER TABLE titles_1 DROP FOREIGN KEY titles_1_ibfk_1; 
-- 인덱스 추가;
ALTER TABLE titles_1 ADD INDEX emp_no(emp_no);


SHOW FULL COLUMNS FROM SALARIES_1;

CREATE TABLE departments_1(
	dept_no CHAR(4) NOT NULL
	,dept_name VARCHAR(40) NOT NULL
	,CONSTRAINT PK_departments_dept_no PRIMARY KEY(dept_no) 
);  

CREATE TABLE dept_emp_1(
	EMP_NO INT(11) NOT NULL
	,dept_no CHAR(4) NOT NULL
	,FROM_DATE DATE NOT NULL
	,TO_DATE DATE NOT NULL
	,PRIMARY KEY (EMP_NO)
	,CONSTRAINT fk_dept_emp_no foreign key (dept_NO) REFERENCES departments_1(dept_NO)
);
COMMIT;
DROP TABLE dept_emp_1;
-- 외래키 이름 설정 및 추가;
alter table dept_emp_1 ADD CONSTRAINT fk_dept_emp_no 
foreign key (EMP_NO) REFERENCES employees_1(EMP_NO);

